name: Build and upload

on:
  push:
    tags:
      - '*-emqx-*'
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
      create_release:
        type: boolean
        required: true
        default: false

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    container:
      image: erlang:25
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.tag }}
    - name: build
      run: |
        git config --global --add safe.directory $(pwd)
        ./bootstrap
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push' || inputs.create_release
      with:
        name: Release ${{ github.ref_name }}
        files: ./rebar3
        draft: false
        prerelease: false
