name: Common Test

on:
  pull_request:
    branches:
      - '*-emqx'
  push:
    branches:
      - '*-emqx'

jobs:
  linux:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        otp_version: [24, 25, 26, 27]

    container:
      image: erlang:${{ matrix.otp_version }}

    env:
      LATEST_OTP_RELEASE: 27

    steps:
    - uses: actions/checkout@v4.2.0
      with:
        fetch-depth: 0
    - name: build
      run: |
        git config --global --add safe.directory $(pwd)
        ./bootstrap
    - name: CT tests
      run: ./rebar3 ct
    - shell: bash
      name: Dialyzer
      run: |
        [[ "${{ matrix.otp_version }}" != "${{ env.LATEST_OTP_RELEASE }}" ]] || (./rebar3 clean -a && ./rebar3 as dialyzer dialyzer)

  macos:
    name: Test on MacOS
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        otp_version: [24, 25, 26, 27]

    steps:
    - uses: actions/checkout@v4.2.0
      with:
        fetch-depth: 0
    - name: Install erlang
      run: |
        brew install erlang@${{ matrix.otp_version }}
        echo "PATH=$(brew --prefix)/opt/erlang@${{ matrix.otp_version }}/bin:$PATH" >> $GITHUB_ENV
    - name: Compile
      run: ./bootstrap
    - name: CT tests
      run: ./rebar3 ct
